### ISSUE TITLE
Testing microservices that are running on Kubernetes error

### ISSUE THREAD

**Issue by krzysztof-dzik** [OpenLiberty/draft-guide-istio#139]
/SystemEndpointIT.java:[3,36] package org.junit.jupiter.api does not exist

**Comment by gkwan-ibm** [comment]
hi @krzysztof-dzik 
Would you tell us what you did?
- You created SystemEndpointIT.java at the `start/src/test/java/it/io/openliberty/guides/system/` directory and then ran `mvn test-compile`?

We does not see any complication error when do that.

**Comment by gkwan-ibm** [comment]
hi @krzysztof-dzik we are closing this issue. You may reopen it and tell us what you did in detail.
