### ISSUE TITLE
Feedback from Emily

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/draft-guide-istio#20]
1. add a link to istio.io on the section What is Istio? Istio should be made to hypelink
2. I suggest to display and explain hello.yaml and traffic.yaml in this case, you can see the port mapping to 31380 which was mentioned later.
3. set-live.bat and set-live to github repo so that you don't spend two pages to list them as they are not the main focus of this guide
4. I don't quite understand why you need to create the version 3 of the app and then automate the weight. Can you explain in the doc?

**Comment by proubatsis** [comment]
PR Merged
