### ISSUE TITLE
Tommy's Review

### ISSUE THREAD

**Issue by wojtczat** [OpenLiberty/draft-guide-istio#24]
## getting started
- [x] code commands are saying to clone repo “guide-istio-intro” while the repo title is just “guide-istio”
## what is istio
- [x] “istio is a service mesh” this comes out of nowhere and doesn’t flow well with the paragraph 
## Deploying version 2 of the hello microservice
- [x] both “{“greeting":"hello","version":"2.0-SNAPSHOT”}“ responses do not need to be copied
## Great work! You’re done!
- [x] add “in Open Liberty” to end of sentence

**Comment by proubatsis** [comment]
@wojtczat When we rename the repo to publish it will be `guide-istio-intro`

**Comment by proubatsis** [comment]
PR Merged
