### ISSUE TITLE
Update SEO title and description

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-istio#27]
- Should better capture what the guide is trying to convey
- Should be made consistent with the other (recent) guides

**Comment by yeekangc** [comment]
Consider something like the below:

:page-seo-title: Managing microservice traffic using Istio
:page-seo-description: A tutorial on how to manage microservice traffic with Istio using blue-green deployment as an example

@gkwan-ibm @evelinec

**Comment by proubatsis** [comment]
PR Merged #28
