### ISSUE TITLE
Content review

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-istio#3]
- [x] Explore how to route traffic to different versions of the same service using Istio and Kubernetes. => "route traffic" sounds vague. Need something more specific here. 

- [x] The two microservices that you will deploy are called inventory and system, they are provided for you under the start directory. => I think we don't need to mention "under the start directory" here, especially this is the intro. 

- [x] The system service provides information about the system that the service is running on, specifically the hostname, username, and operating system of your computer. => I think you can state that the `system` service retrieves the system properties of the system, instead of saying "provides information about the system", to be more specific. Then "hostname, username, and operating system of your computer" can be an example of some of the system properties. 

- [x] Double check the standard of spelling "cli", whether it's cap'ed or small letters. 

- [x] In this guide the istioctl tool will be used to apply routing rules to determine which version of the inventory microservice will be accepting requests based on an x-version header.
=> Do not use "In this guide". You can put it as, "You will use the `istioctl` tool to apply.."
=> I think you may not need to refer to the "x-version" header here as it's the intro. Including it here without further explanation of how it work, seems like something is missing. 

- [x] Do not use the word "please" in the readme

- [x] This link here "[https://zipkin.io/]Zipkin" doesn't show up properly on the website

- [x] creates/updates => use word "or" instead of "/"

- [ ] The "---" in the yaml file can be removed? It's colour coded on the website.

- [ ] `<ip-address>:<port>` => it's be easier for user if there's specific ip and port being specified. 

- [x] Follow the guideline for the follow areas: 

- Listing blocks example: Create the inventory manager class in the `src/main/java/io/openliberty/guides/inventory/InventoryManager.java` file:
- Wrap lines at 88 characters to maintain readability in editors and on the website.

- [x] Do not use directional words like, "following", "above", "below" etc. 

- [x] "Why use Istio" section => the three paragraphs can be reorganized a little. Perhaps to mention all of the benefits first, and then you state which one will be covered in this guide.

**Comment by evelinec** [comment]
The changes look good. You may want to manually format some of the assert lines to make it display nicely on the website.

**Comment by proubatsis** [comment]
Does this look better @evelinec ? It is more consistent with how the other guides do it now.

---

# Old

![image](https://user-images.githubusercontent.com/8409464/42944921-f97db57e-8b34-11e8-961a-ab1bf0fc0061.png)

# New

![image](https://user-images.githubusercontent.com/8409464/42944950-0ca25d4e-8b35-11e8-8841-136d0ab93047.png)

**Comment by evelinec** [comment]
Looks good.
